global using MediatR;
global using AutoMapper;
global using Ambev.DeveloperEvaluation.Domain.Enums;
global using Ambev.DeveloperEvaluation.Domain.Entities;
global using Ambev.DeveloperEvaluation.Domain.Repositories;
global using Ambev.DeveloperEvaluation.Domain.ValueObjects;
global using Ambev.DeveloperEvaluation.Domain.Exceptions;
global using Ambev.DeveloperEvaluation.Common.Security;
global using FluentValidation;
